config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :projects, only: [:new , :create, :show, :edit, :update, :index, :destroy] do
    member do
      patch '/fav', to: 'projects#fav'
    end

    resources :memories, only: [:new , :create, :show, :edit, :update, :index]
    resources :cards, only: [:index, :show]
    resources :games, only: [:index, :show]
    get :win
    get :thanks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :scenario
  has_many :memories
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user
  belongs_to :card, optional: true
  belongs_to :project
  has_one_attached :photo
  validate :memories_limit

  def memories_limit
    if project.user != user && project.memories.where(user: user).count >= 3
      errors.add(:photo, :blank, message: ": pas plus de 3 par projet")
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :scenario, optional: true
  has_one_attached :photo
  has_many :memories
  validates :description, presence: true
  validates :title, presence: true
  validates :besty_first_name, presence: true
  validates :photo, presence: true
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  has_many :cards, dependent: :destroy
  has_many :projects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rediriger apres log in
  def after_sign_in_path_for(_resource)
    projects_path
  end

  def after_sign_up_path_for(_resource)
    projects_path
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_project, :set_memories

  def index
    @cards = policy_scope(Card)
    @cards = @cards.where(scenario: @project.scenario)
  end

  def show
    @card = Card.find(params[:id])
    @available_memories = @memories.where(card_id: nil)
    @used_memories = @memories.where.not(card_id: nil)
    @card_memory = @memories.find_by(card: @card)
    authorize @card
  end

  private

  def projects_params
    params.require(:project).permit(:scenario_id)
  end

  def set_memories
    @memories = policy_scope(@project.memories)
  end

  def set_project
    @project = Project.find(params[:project_id])
    authorize @project
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :win]

  def skip_pundit?
    true
  end

  def index
    @project = Project.find(params[:project_id])
    @card = @project.scenario.cards.first
  end

  def show
    @project = Project.find(params[:project_id])
    @card = Card.find(params[:id])
    @cards = @project.scenario.cards
    @next_card = @cards[@cards.index(@card) + 1]
    @memory = @card.memories.where(project_id: @project).first
  end


end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def show
    project = Project.find_by(code: params[:id])
    authorize project
    redirect_to project_path(project)
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_project
  before_action :set_memory, except: [:create, :new, :index]
  def index
    if current_user == @project.user
      @memories = policy_scope(@project.memories)
    else
      @memories = policy_scope(@project.memories.where(user: current_user))
    end
  end

  def show
    @memories = @project.memories
    authorize @memories
  end

  def edit
    authorize @memory
  end

  def update
    authorize @memory
    @memories = @project.memories
    # chercher les memories qui ont la meme card_id
    same_card_memories = @memories.where(card_id: memories_params[:card_id])
    # vider le card_id
    same_card_memories.update_all(card_id: nil)
    @memory.update(memories_params)
    redirect_to project_cards_path(@project, anchor: "card_#{@memory.card_id}")
  end

  def new
    @memory = Memory.new
    authorize @memory
  end

  def create
    @memory = Memory.new(memories_params)
    @memory.user = current_user
    @memory.project = @project
    @memory.legend = @memory.legend.capitalize
    authorize @memory
    if @memory.save
      redirect_to project_memories_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @memory
    @memory.destroy
    redirect_to project_memory_path(@memory)
  end

  private

  def memories_params
    params.require(:memory).permit(:legend, :card_id, :response, :photo)

  end

  def set_memory
    @memory = Memory.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @current_user_projects = policy_scope(Project.where(user_id: current_user))
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_projects, only: [:show, :update, :edit, :destroy, :fav]

  def index
    @current_user_projects = policy_scope(Project.where(user_id: current_user))
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(projects_params)
    @project.user = current_user
    @project.favorite = false
    @project.code = SecureRandom.hex(5)
    authorize @project
    if @project.save
      redirect_to projects_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @scenarios = Scenario.all
    authorize @project
  end

  def update
    authorize @project
    if @project.update(projects_params)
      redirect_to project_cards_path(@project), notice: "Scenario choisi"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def win
    @project = Project.find(params[:project_id])
    authorize @project
    @memories = @project.memories
  end

  def thanks
    @project = Project.find(params[:project_id])
    authorize @project
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, status: :see_other
  end

  def fav
    @fav = Project.find_by(favorite: true)
    @fav&.update(favorite: false)

    if @project.favorite
      @project.update(favorite: false)
    else
      @project.update(favorite: true)
    end

    render json: { favorite: @project.favorite, previous_favorite: @fav&.id }

    authorize @project
  end

  private

  def projects_params
    params.require(:project).permit(:title, :description, :photo, :scenario_id, :favorite, :besty_first_name)
  end

  def set_projects
    @project = Project.find(params[:id])
    authorize @project
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

def edit
  @scenarios = Scenario.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/index.html.erb
<h1 class="h1" ></h1>

<% if @cards.any? %>

  <div class="game-cards">
    <% @cards.each do |card| %>
      <div class="card-category-game-2" id="card_<%= card.id %>">
        <% card_memory = @memories.find_by(card: card) %>

        <% if card_memory %>
          <div class="card-image">
            <%= link_to project_card_path(@project, card) do %>
              <i class="fa-solid fa-pen-to-square card-game-edit "></i>
            <% end %>
            <%= cl_image_tag card_memory.photo.key, class: "d-block w-100"%> <br>
              <h3 class="h3 text-justify"> <%= card.question %> ? </h3>
          </div>
          <%# Bouton masque pour edition depuis icone %>
          <%# <div class= "d-flex justify-content-center"> %>
            <%#= link_to "Sélectionner un souvenir", project_card_path(@project, card), class: "btn btn-flat" %>
          <%# </div> %>
          <div class="d-flex">
            <p class="p w-25"><%#= card_memory.legend %> </p>
          </div>
          <div class="card-form">
            <%= simple_form_for [@project, card_memory], html: {"data-turbo": false} do |f| %>
              <%= f.input :response, label: "Réponse :", label_html: { class: 'p' }, input_html: { class: 'p' }%>
              <div class= "d-flex justify-content-center">
                <%= f.submit class: "btn btn-flat w-100", value: "Enregistrer la réponse" %>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class= "d-block " >
          <h3 class="h3 text-justify"> <%= card.question %> ? </h3>
            <%= link_to "Choisir un souvenir", project_card_path(@project, card), class: "btn btn-flat w-100"%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="p">Le scenario est vide</p>
<% end %>

<div class="d-flex justify-content-end marg-right">
  <%= link_to "Simuler le jeu",  project_games_path(@project), class: "btn btn-flat" %>
</div>

<%= render "shared/navbar_dark" %>

app/views/cards/show.html.erb
<div class="grey-banner container">
  <h1 class="h1 bg-white margin-show-list"> Souvenirs disponibles </h1>
  <p class="p bg-white"><%= @card.question %> ?</p>

  <div class="cards">
    <% @available_memories.each do |memory| %>
        <div class="card-category-game bg-white">
          <%= cl_image_tag memory.photo.key , class: "img-card d-block w-100"%>
          <div>
            <p class="h4"><%=  memory.legend %> </p>
          </div>
          <div>
            <%= simple_form_for [@project, memory], html: {"data-turbo": false} do |f| %>
              <%= f.hidden_field :card_id, value: @card.id %>
              <% if @card_memory %>
                <%= f.hidden_field :response, value: @card_memory.response %>
              <% end %>
              <%= f.submit class: "btn btn-flat", value: "Compléter le souvenir"  %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>

  <h1 class="h1"> Souvenirs déjà utilisés </h1>

  <div class="cards">
    <% @used_memories.each do |memory| %>

        <div class="card-category-game bg-white">
          <%= cl_image_tag memory.photo.key, class: "img-card d-block w-100"%>


          <div>
            <p><%=  memory.legend %> </p>
          </div>

          <div>
            <p class="p">Ce souvenir est associé à la question :</p>
            <%= memory.card.question%>
          </div>

        </div>

    <% end %>
  </div>
</div>
<%= render "shared/navbar_dark" %>

app/views/games/index.html.erb
<div class="container">
  <div class="center_btn">
    <div class="index_btn">
    <%= link_to image_tag("vira-transp.gif", :height => "170", :width => "170"), project_game_path(@project, @card), class:"a_btn" %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="grey-banner">
  <div class="container ">
   <h1 class="h1 margin-show-list"> A toi de jouer !</h1>
    <div class="game-cards bg-white ">
      <p class= "$body-font p"> <%= @card.question %> ?</p>
      <%= cl_image_tag @memory.photo.key, class: "img-card-game d-block w-100 bg-white"%>
      <div class= "bg-white">
      <p class="$body-font h4 margin-show-list bg-white mt-5"> Réponse :</p>
    </div>
    <div data-controller="hiddenbutton" data-hiddenbutton-response-value="<%=@memory.response%>">
    <input type="text" data-hiddenbutton-target="input" data-action="keyup->hiddenbutton#responseTrue" class="input-field w-100 bg-white mb-5">

        <% if @next_card == nil %>
          <%=  link_to " 🎉 Surprise 🎉 ",   project_win_path(@project), "data-hiddenbutton-target": "button", class: "btn btn-flat w-100", style:"display: none"%>
        <% else %>
          <%=  link_to "Question suivante",  project_game_path(@project, @next_card), "data-hiddenbutton-target": "button", class: "btn btn-flat w-100", style:"display: none"%>
        <% end %>
        <br>
    </div>
   </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeMyBest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
  <%# <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <div class="content-wrapper <%= "game-wrapper" if controller_name == "games" && action_name == "index" %>">
      <%= yield %>
    </div>
  <%#= render "shared/footer" %>

  </body>
</html>

app/views/memories/_form.html.erb
<%= simple_form_for([@project, @memory]) do |f| %>
  <%= f.input :photo, as: :file, label: "Vos photos :", input_html: { class: 'fileinput-button p' }, label_html: { class: 'h2' } %>
  <p> <br></p>
  <%= f.input :legend, label: "Description de votre souvenir :", input_html: { class: 'input-field bg-white' }, label_html: { class: 'h2 bg-white' }  %>
  <%= f.submit class: "w-100 btn btn-flat margin-top-card", value: "Ajouter" %>
<% end %>

app/views/memories/index.html.erb
<div class="grey-banner">
  <div class="container">
  <h1 class="h1 margin-top-card bg-white"> Mes souvenirs partagés :  </h1>

  <%= link_to "Ajouter un souvenir", new_project_memory_path(@project), :class => 'btn btn-flat' %>
  <div class="cards">
    <% @memories.each do |memory| %>
      <% if memory.present? %>
      <div class="card-category d-block m-3 bg-white">
        <%= cl_image_tag memory.photo.key, class: "img-card d-block w-100"%>
          <div>
            <p class="p_card_memo_index bg-white"><%=  memory.legend %> </p>
          </div>
      <% end %>
      </div>
    <% end %>
  </div>
    <% if current_user != @project.user %>
      <%= link_to "valider vos souvenirs", project_thanks_path, :class => 'btn btn-flat' %>
    <% end %>
  </div>
</div>

<%= render "shared/navbar_dark" %>

app/views/memories/new.html.erb
<div class="grey-banner">
  <div class="container my-2">
    <% if current_user == @project.user %>
      <h1 class="h1 bg-white margin-top-card">Ajouter un nouveau souvenir ! </h1>
    <% else %>
      <h1 class="h1">Ajouter un nouveau souvenir !</h1>
      <p class="p">Attention vous êtes limité à 3 souvenirs! choisissez bien !</p>
    <% end %>
    <%= render "form", memory: @memory %>
    <div>
      <%= link_to project_memories_path(@project) do %>
      <i class="fa-solid fa-arrow-left-long marge-top-retour"></i>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/navbar_dark" %>

app/views/pages/home.html.erb
<div class="home-banner">
  <p class="line-1 anim-typewriter">La vie est un jeu</p>
  <% if @current_user_projects.empty? %>

      <%= link_to "GO", new_project_path, class: "btn banner-btn fw-bold h2"%>

      <%= link_to "GO", new_project_path, class: "btn banner-btn fw-bold"%>

    <% else %>
      <%= link_to "GO", projects_path, class: "btn banner-btn fw-bold"%>
    <% end %>
</div>

app/views/projects/_form.html.erb
<div class=" mt-5 my-2 h3">
  <p></p>
  <div class ="bg-white">
  <%= simple_form_for(project) do |f| %>
    <div class="bg-white mt-3 mb-3">
      <%= f.input :title, label: "Titre du jeu : ",  input_html: { class: 'input-field bg-white' } %>
    </div>
    <div class ="mb-3">
      <%= f.input :besty_first_name, label: "Pour qui crées-tu ce jeu ? ",  input_html: { class: 'input-field bg-white' } %>
    </div>
    <div class =" mb-3">
      <%= f.input :description, label: "Description du jeu : ", input_html: { class: 'input-field bg-white' }  %>
    </div>
    <div class =" mb-3">
    <%= f.input :photo, as: :file, label: "Photo du jeu :", input_html: { class: 'fileinput-button bg-white' } %>
    <p> <br></p>
    <div class="mt-2">
      <%= f.submit class: "w-100 btn btn-flat",  value: "Créer ton jeu"%>
    </div>
  <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container margin-top-card">
  <h1 class= "h1 mx-4 mt-3 text-center"> Choisis un jeu </h1>
  <div class="cards">
    <%= form_with url: project_path(@project), method: :patch, html: { turbo: false} do |form|%>
        <input type="hidden" name="_method" value="patch">
    <% @scenarios.each do |scenario| %>
      <label>
      <div class="scenario-card">
      <input type="radio" name= "project[scenario_id]" value="<%= scenario.id%>">
      <div class="backgroundlin">
          <%= image_tag scenario.img,  class:"img-scenario-card "%>
      </div>
          <p class="scenario-title"> <%#= scenario.title%> </p>
      </div>
      </label>
      <% end  %>
      <button type="submit" class="btn btn-flat w-100 mt-3"> Valider </button>
    <% end %>
  </div>
</div>

<%= render "shared/navbar_dark" %>

app/views/projects/index.html.erb
<style>
  a, p, h2, i{
 text-decoration:  none;
}
</style>

<div class="grey-banner">

  <div class="container mt-2">
    <h1 class="bienvenue bg-white margin-top-card "> Bienvenue <%= @current_user.first_name %> 👋 </h1>
    <p class="h3 mt-4 mb-4"> Un de tes amis fête bientôt son anniversaire ? <br>
    Offre-lui une expérience unique avec BE MY BEST ! </p>

    <% if @current_user_projects.empty? %>
      <p class="p"><%= link_to "Créer un nouveau jeu 🎨", new_project_path, class: "btn btn-flat w-100"%></p>
    <% else %>
      <%= link_to "Créer un nouveau jeu 🎨", new_project_path, class: "btn btn-flat w-100 my-2"%>
      <h2 class= " my-4 m-3 h1"> <i class="fa-solid fa-puzzle-piece"></i> Mes jeux : </h2>

      <div class="cards" data-controller="favorite">
        <% @current_user_projects.each do |project| %>
          <div class="card-category m-3">
          <%= link_to project_path(project) do %>
            <% if project.photo.attached? %>
              <%= cl_image_tag project.photo.key, class: "img-card w-100"%>

              <div class="card-description-p d-block mb-2">

                <div class="d-flex justify-content-between">
                  <h2 class="h2"> <%= project.title %> </h2>
                  <% if project.favorite %>
                    <i class="fa-solid fa-heart card-project-favorite mx-2" data-action="click->favorite#fav" data-favorite-project-id-param="<%= project.id %>" ></i>
                  <% else %>
                    <i class="fa-regular fa-heart card-project-favorite mx-2" data-action="click->favorite#fav" data-favorite-project-id-param="<%= project.id %>"></i>
                  <% end %>
                </div>

                <div class="d-flex justify-content-between">
                  <p class="p">  <%= project.description.length > 25 ? "#{project.description.first(25)}..." : project.description %></p>
                  <%= link_to project_path(project), data: {turbo_method: :delete, turbo_confirm: "Confirmes-tu la suppression de ce projet ?"} do %>
                    <i class="fa-solid fa-trash card-project-trash mx-2"></i>
                  <% end %>
                </div>

              </div>
            <% end %>

          </div>

        <% end %>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

<%= render "shared/navbar_dark" %>

app/views/projects/new.html.erb
<div class="grey-banner margin-top-card ">
  <h1 class="h1 mt-3 mb-2 bg-white margin-top-card"> Créer un nouveau jeu</h1>
  <div class="container">
    <%= render "form", project: @project %>
  </div>
</div>
<%= render "shared/navbar_dark" %>

app/views/projects/show.html.erb
<style>
  i, a{
 text-decoration:  none;
 color:#2c3a89;
}
</style>

<div class="grey-banner">
  <div class="image_button">
    <div>
      <p class="p bg-white"> <%= cl_image_tag @project.photo.key, class: "w-100 photo-project-id" %> </p>
    </div>
    <div class="card-project-relative margin-show-project">
      <div class="text">
        <h1 class="h1 bg-white" > <%=  @project.title %> </h1>
      </div>
      <div>
        <p class="p bg-white" > <%=  @project.description %> </p>
      </div>
    </div>
    <div class = "d-flex justify-content-center">
    <%= link_to  project_memories_path(@project), class: "h2 add-photo-show" do %>
      <h1 class ="plus"> + </h1>
      <i class="fa-solid fa-camera-retro fa-3x bg-white mx-2"></i>
     <% end %>
     </div>
  </div>

  <div class="container mt-2">
    <div class="accordion" id="accordionExample">
    <div class="accordion-item mx-2">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed h3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Récolte les souvenirs
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body p">
          <strong>Invite du monde</strong> pour récolter le plus de souvenirs !
          <div class="icon-link-project">
            <a href="https://wa.me/?text=click%20sur%20ce%20lien%20pour%20participer%20http://www.bmybest.me//projects/<%= @project.id %>/memories/new"><i class="fa-brands fa-whatsapp fa-sm"></i></a>
            <a href="mailto:?subject=Participes au cadeau BMyBest&body=click%20sur%20ce%20lien%20pour%20participer%20http://www.bmybest.me//projects/<%= @project.id %>/memories/new"><i class="fa-solid fa-envelope fa-sm"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="accordion-item mx-2">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed h3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Le jeu est prêt ? Envoie-lui le lien !
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body p">
          <strong>Tout est prêt ?</strong>
            Alors c'est le moment d'envoyer son cadeau à <%= @project.besty_first_name %>
          <div class="icon-link-project">
            <a href="https://wa.me/?text=click%20sur%20ce%20lien%20pour%20participer%20http://www.bmybest.me//projects/<%= @project.id %>/games"><i class="fa-brands fa-whatsapp fa-sm"></i></a>
            <a href="mailto:?subject=Participes au cadeau BMyBest&body=click%20sur%20ce%20lien%20pour%20participer%20http://www.bmybest.me//projects/<%= @project.id %>/games"><i class="fa-solid fa-envelope fa-sm"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div>
      <%= link_to "Personnaliser le jeu ", edit_project_path(@project), class: "btn btn-flat w-100 mt-5 "%> </p>
    </div>
  </div>
</div>

<%= render "shared/navbar_dark" %>

app/views/projects/thanks.html.erb
<div class="congrats-centered grey-banner">
  <%= image_tag "dicaprio.gif", class: "congrats_gif" %>
</div>
<%= render "shared/navbar_dark" %>

app/views/projects/win.html.erb
<div class="finish-banner">
<br> <br>
  <h1 class="end-title">Merci d'avoir joué</h1>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    L'équipe BeMyBest vous remercie pour votre visite <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">